import {StyleSheet} from 'react-native';
import {heightToDP} from 'react-native-responsive-screens';
import colors from '../../../assets/colors';
import Fonts from '../../../assets/fonts';
import responsiveUtils from '../../../utils/responsiveUtils';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    height: '100%',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 30,
  },
  backButton: {
    alignSelf: 'flex-start',
    paddingLeft: '6%',
    zIndex: 2,
  },
  headerTitle: {
    fontFamily: Fonts.FigtreeSemi,
    fontSize: responsiveUtils.relativeFontSize(23),
    color: colors.WHITE,
    textAlign: 'center',
    position: 'absolute',
    alignSelf: 'center',
    width: '100%',
  },
  borderBottomLine: {
    width: '100%',
    borderBottomColor: colors.WHITE,
    opacity: 0.35,
    borderBottomWidth: 1,
  },
  content: {
    flex: 1,
    // width: '80%',
    paddingHorizontal: heightToDP('3%'),
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'flex-start',
    paddingTop: heightToDP('5%'),
  },
  scrollContent: {
    paddingBottom: heightToDP('6%'),
  },
  logoContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: heightToDP('5%'),
  },
  logo: {
    height: responsiveUtils.relativeHeight(16.84),
    width: responsiveUtils.relativeHeight(13.84),
  },
  textWrapper: {
    width: '70%',
  },
  titleText: {
    fontSize: responsiveUtils.relativeFontSize(19),
    color: colors.WHITE,
    fontFamily: Fonts.FigtreeSemi,
    textAlign: 'center',
    marginBottom: heightToDP('4.183%'),
  },
  statusCard: {
    width: '100%',
    borderRadius: 28,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    backgroundColor: 'rgba(0,0,0,0.25)',
    paddingVertical: heightToDP('2%'),
    paddingHorizontal: heightToDP('2.5%'),
    marginBottom: heightToDP('3%'),
  },
  statusLabel: {
    fontFamily: Fonts.FigtreeSemi,
    fontSize: responsiveUtils.relativeFontSize(18),
    color: colors.WHITE,
    marginBottom: 6,
    textAlign: 'center',
  },
  statusDescription: {
    fontFamily: Fonts.FigtreeLight,
    fontSize: responsiveUtils.relativeFontSize(14),
    color: colors.WHITE,
    opacity: 0.85,
    textAlign: 'center',
    marginBottom: heightToDP('1.5%'),
  },
  statusMetaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  statusMetaLabel: {
    fontFamily: Fonts.FigtreeRegular,
    color: 'rgba(255,255,255,0.75)',
    fontSize: responsiveUtils.relativeFontSize(13),
  },
  statusMetaValue: {
    fontFamily: Fonts.FigtreeSemi,
    color: colors.WHITE,
    fontSize: responsiveUtils.relativeFontSize(13),
  },
  statusHint: {
    fontFamily: Fonts.FigtreeLight,
    color: 'rgba(255,255,255,0.75)',
    fontSize: responsiveUtils.relativeFontSize(12),
    marginTop: heightToDP('1.2%'),
    textAlign: 'center',
  },
  manageButton: {
    marginTop: heightToDP('1.8%'),
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.4)',
    paddingVertical: heightToDP('1%'),
    alignItems: 'center',
  },
  manageButtonText: {
    fontFamily: Fonts.FigtreeMedium,
    color: colors.WHITE,
    fontSize: responsiveUtils.relativeFontSize(13),
  },
  planCardDisabled: {
    opacity: 0.6,
  },
  currentPlanNote: {
    marginTop: heightToDP('1%'),
    textAlign: 'center',
    fontFamily: Fonts.FigtreeMedium,
    color: colors.WHITE,
    fontSize: responsiveUtils.relativeFontSize(12),
  },
  buttonContainer: {
    width: '100%',
    paddingHorizontal: heightToDP('3%'),
    marginTop: heightToDP('4%'),
    alignItems: 'center',
  },
  continueButton: {
    width: '100%',
    backgroundColor: colors.WHITE,
    borderRadius: 30,
    paddingVertical: heightToDP('2%'),
    paddingHorizontal: heightToDP('4%'),
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 50,
    marginBottom: heightToDP('2%'),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  continueButtonDisabled: {
    opacity: 0.6,
  },
  continueButtonText: {
    fontSize: responsiveUtils.relativeFontSize(18),
    color: '#000',
    fontFamily: Fonts.FigtreeSemi,
    fontWeight: '600',
  },
  restoreButton: {
    width: '100%',
    paddingVertical: heightToDP('1.5%'),
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: heightToDP('2%'),
  },
  restoreButtonText: {
    fontSize: responsiveUtils.relativeFontSize(14),
    color: colors.WHITE,
    fontFamily: Fonts.FigtreeRegular,
    textDecorationLine: 'underline',
  },
  legalTextContainer: {
    width: '100%',
    paddingHorizontal: heightToDP('2%'),
    marginTop: heightToDP('1%'),
    alignItems: 'center',
  },
  legalText: {
    fontSize: responsiveUtils.relativeFontSize(12),
    color: colors.WHITE,
    fontFamily: Fonts.FigtreeRegular,
    textAlign: 'center',
    lineHeight: responsiveUtils.relativeFontSize(16),
    opacity: 0.8,
  },
  legalLink: {
    fontSize: responsiveUtils.relativeFontSize(12),
    color: colors.WHITE,
    fontFamily: Fonts.FigtreeRegular,
    textDecorationLine: 'underline',
    opacity: 1,
  },
});
