const routes = {
  SPLASH_SCREEN: 'SplashScreen',
  SIGN_IN: 'SignIn',
  SIGN_UP: 'SignUp',
  CONNECT: 'Connect',
  SIGN_UP_EMAIL: 'SignUpEmail',
  SETTINGS: 'Settings',
  SIGN_IN_EMAIL: 'SignInEmail',
  FORGOT_PASSWORD: 'ForgotPassword',
  SIGN_UP_PURPOSE: 'SignUpPurpose',
  HOME: 'Home',
  FREQUENCIES: 'Frequencies',
  MOOD: 'Mood',
  ALLFREQUENCIES: 'AllFrequencies',
  ACCOUNT_INFO: 'AccountInformation',
  EDIT_USER_INFO: 'EditUserInfo',
  SET_PASSWORD: 'SetPassword',
  SUBSCRIPTIONS: 'Subscriptions',
  NOTIFICATIONS: 'Notifications',
  MINDFUL_REMINDER: 'MindfulReminder',
  BEDTIME_REMINDER: 'BedtimeReminder',
  INVITE_FRIENDS: 'InviteFriends',
  VOICE_GUIDES: 'VoiceGuides',
  ABOUT: 'About',
  PRIVACY_SECURITY: 'PrivacySecurity',
  TERMS_CONDITION: 'TermsCondition',
  SAVED_AUDIOS: 'SavedAudios',
  SAVED_VIDEOS: 'SavedVideos',
  FULLSCREEN_VIDEO: 'FullScreenVideo',
} as const;
export default routes;
